version: "3"
services:
    schedular:
        image: node:8-alpine
        container_name: crontest
        volumes:
            - ./cron/root:/etc/crontabs/root
            - ./cron/1min-jobs.sh:/home/cronjobs/1min-jobs.sh
        command: "sh -c 'apk update && apk add tzdata &&\
            apk add --no-cache curl &&\
            cp /usr/share/zoneinfo/Asia/Singapore /etc/localtime &&\
            echo \"Asia/Singapore\" > /etc/timezone &&\
            apk del tzdata && rm -rf /var/cache/apk/* &&\
            /usr/sbin/crond -f'"
